### ISSUE TITLE
Uso de labels

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#13]
Olá,
Acho que seria interessante definir o uso de labels para ajudar na organização das issues aqui no GitHub.
Pensei nas seguintes labels (já criadas):
- **ajude**  
  Algo para que iniciantes que desejam partipar da equipe demonstrem suas habilidades.
- **governança**  
  Issues para definirmos processos da equipe. Por exemplo: esta issue
- **tarefa**  
  Alguma coisa que devemos fazer dentro da organização io.js, provavelmente vindo da equipe principal. Por exemplo: tradução de posts

**Comment by danilovaz** [comment]
@gustavohenke e se criar uma label só para tradução? Ficando com 4 labels: ajude, governança, tarefa e tradução. Seria mais interessante e mais organizado ter uma label apenas para traduções.

**Comment by danilovaz** [comment]
adicionei uma label chamada discussão, para tópicos que têm como objetivo discutir algo a cerca do repositório e que não necessariamente se encaixe nas outras labels, como por exemplo, definição de pt-pt ou pt-br

**Comment by fixe** [comment]
Acho que devíamos fazer como os outros fazem: labels em Inglês, etc. Ver [aqui](https://github.com/iojs/iojs-es/issues).

**Comment by ruiquelhas** [comment]
Totalmente de acordo com o @fixe. Já expressei a minha opinião sobre o assunto - #6.

**Comment by gustavohenke** [comment]
Como já foram traduzidas os labels, vou fechar. Acho que não tem muito mais o que se discutir, depois podemos criar um markdown no repositório para comentar melhor estas regras.
