### ISSUE TITLE
Termos técnicos

### ISSUE THREAD

**Issue by ruiquelhas** [nodejs/nodejs-pt#14]
Enquanto não há fumo branco no #6, abro mais um issue em Português.

Tendo em conta a discussão actual, e olhando para o draft do primeiro blog post, existem termos técnicos (o que há partida será norma em todos eles) como `commit`, `tracing`, etc. Estão a pensar em aplicar alguma regra na tradução destes? Eu sou da opinião que se devem manter em Inglês.

**Comment by gustavohenke** [comment]
Também acho que termos técnicos podem ficar em inglês.

**Comment by ruimarinho** [comment]
Eu também voto em manter em inglês.

**Comment by danilovaz** [comment]
termos técnicos também acho que podem ficar em inglês; não faria muito sentido commit, push, pull, tracing, debug, etc em portugês...

**Comment by leonardosalles** [comment]
Também concordo, termos técnicos em inglês, as cabeças de todos já estão acostumadas com esses termos, não vejo dificuldade em manter

**Comment by danilovaz** [comment]
creio que entramos em consenso, estou fechando essa issue.
