### ISSUE TITLE
Tradução do Site - pt-BR

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#15]
Instruções: https://github.com/iojs/website/blob/master/TRANSLATION.md
Arquivos fonte: https://github.com/iojs/website/tree/master/content/pt_BR
Pull request: iojs/website#150

**Comment by danilovaz** [comment]
boa :+1: precisando de algo, só chamar ^^

**Comment by gustavohenke** [comment]
Se possível, ir revisando lá no PR do website. É necessário um +1 lá depois que estiver pronto pra ser aceito.

**Comment by gustavohenke** [comment]
Ou, mesmo contribuindo no meu fork..

**Comment by danilovaz** [comment]
beleza, vou dar uma conferida :+1:

**Comment by danilovaz** [comment]
conferi o PR, me parece tudo certo.

**Comment by gustavohenke** [comment]
Tem mais a vir. Todo o FAQ e a documentação sobre ES6...

**Comment by gustavohenke** [comment]
Se alguém mais quiser contribuir, só me falar que libero acesso no fork!

**Comment by danilovaz** [comment]
beleza, estou traduzindo o FAQ :+1:

**Comment by danilovaz** [comment]
Terminei de traduzir a FAQ. Aguardando revisão agora.

**Comment by gustavohenke** [comment]
Finalizada a tradução, obrigado @danilovaz!
Por favor pessoal, nos ajudem revisando o PR iojs/website#150

**Comment by gustavohenke** [comment]
Feito!
