### ISSUE TITLE
Tradução do Site - pt-PT

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#16]
Instruções: https://github.com/iojs/website/blob/master/TRANSLATION.md
Arquivos fonte: https://github.com/iojs/website/tree/master/public/pt_PT
PR: iojs/website#176

**Comment by rogeriopvl** [comment]
PR feito. Alguém pode rever a tradução pff? iojs/website#176

**Comment by gustavohenke** [comment]
O PR foi aceito, fechando!

**Comment by gustavohenke** [comment]
Obrigado @rogeriopvl!
