### ISSUE TITLE
Tradução "io.js and node.js Foundation"

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#18]
https://medium.com/@iojs/io-js-and-a-node-js-foundation-4e14699fb7be

**Comment by danilovaz** [comment]
Traduzindo...

**Comment by danilovaz** [comment]
Pessoal, traduzi esse post. Por favor, quem puder fazer uma revisão.

Obrigado.

https://medium.com/@iojs_pt/e04e0758f1ea

**Comment by gustavohenke** [comment]
@danilovaz, me intrometi e alterei algumas coisas no artigo :confused: 
Se alguém tiver mais alguma consideração, pode deixar uma nota lá ou mesmo aqui, e aí depois podemos fechar, eu acho.

**Comment by danilovaz** [comment]
@gustavohenke tranquilo, a ideia é essa mesmo :smile: estamos em um ritmo bom. mas acho que devemos criar um padrão para agilizar o processo de reviewing/translated, criei uma issue #19 para discutir isso

**Comment by gustavohenke** [comment]
@iojs/iojs-pt, alguém mais poderia revisar o artigo?

Por mim, é :+1:.

**Comment by rogeriopvl** [comment]
Por mim está :+1: 

Mas tenho uma questão: como será relativamente a traduzir os posts em pt_PT ?

**Comment by danilovaz** [comment]
@rogeriopvl os posts serão traduzidos em PT geral, dái peço a ajuda dos membros de Portugal para dar sugestões de palavras que possam ter significados diferentes entre nossas nações, para que tenhamos um texto mais "globalizado" possível em português, indepentende de Portugal ou Brasil. Da mesma forma, o pessoal do Brasil ajuda nas revisões do pessoal de Portugal para usarmos palavras que tenham o mesmo sentido/significado nos dois países =)

A unica parte que terá diferenças de tradução pt-pt e pt-br é o site, conforme tem uma issue aberta aqui para tradução da mesma em pt-pt

**Comment by rogeriopvl** [comment]
@danilovaz ok! :+1:

**Comment by gustavohenke** [comment]
Publiquei!
