### ISSUE TITLE
Aprovação de arquivos em revisão

### ISSUE THREAD

**Issue by danilovaz** [nodejs/nodejs-pt#19]
Galera, visando manter a organização e também tornar ágil e prático nosso processo de reviewing/translated gostaria de propor aqui que os artigos marcados com a label reviewing estarão aptos a ser publicados quando 2 membros da equipe enviarem um :+1:  e caso haja algo a ser arrumado venha seguido de um :-1: e o comentário do que deve ser alterado.

O que acham?

cc @iojs/iojs-pt

**Comment by erickpatrick** [comment]
Por mim, seria o ideal :+1:

Sou quase um "nazista de gramática" e tem algumas coisas que me incomodam em algumas traduções, principalmente, no tocante ao uso de estrangeirismos. Se existe a opção/termo/palavra em português e de fácil entendimento/conhecimento, por que usar o termo em inglês? Se o objetivo é a tradução, façamos da melhor maneira possível.

Claro, não é traduzir tudo ao pé-da-letra, mas, como falei, se existe a opção em português, é preferível à versão estrangeira. Pelo menos para mim.

(Desculpa ter fechado anteriormente, apertei o botão errado sem querer).

**Comment by gustavohenke** [comment]
Por mim :+1: também!

**Comment by danilovaz** [comment]
legal, vamos esperar mais alguns membros expressarem a opinião deles, aí decidimos e fechamos a issue =) valeu galera.

**Comment by rogeriopvl** [comment]
:+1:

**Comment by getuliojr** [comment]
Concordo com o proposto.

**Comment by Glauber** [comment]
![]

**Comment by Glauber** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by Glauber** [comment]
:+1:
