### ISSUE TITLE
Tradução "io.js Week of February 13th 2015"

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#21]
https://medium.com/node-js-javascript/io-js-week-of-february-13th-2015-7846b94074a2

**Comment by gustavohenke** [comment]
Alguém se disponibiliza para esta tradução..?

**Comment by getuliojr** [comment]
Eu faço hoje no almoço.

**Comment by getuliojr** [comment]
Pessoal, podem olhar a tradução e enviar correções ou aprovar a mesma ?

https://medium.com/@getuliojr/77a7e044c211

**Comment by gustavohenke** [comment]
Opa,
Me pede via gitter/e-mail a senha da nossa conta do Medium pra postarmos lá.

**Comment by rogeriopvl** [comment]
> "io.js rompe 10.000 estrelas no GitHub"

A palavra "rompe" creio que é uma expressão muito brasileira, seria melhor algo como "ultrapassa as 10.000 estrelas". O que acham?

O resto da tradução por mim está :+1:

**Comment by alexsantos** [comment]
Concordo com o @rogeriopvl, de resto já dei o meu contributo :+1:

**Comment by getuliojr** [comment]
Ok, Todas as sugestões feitas já foram alteradas. Preciso apenas saber como publicar na página em pt agora. Ainda não recebi os dados. Assim que souber eu concluo e fecho a tarefa.

**Comment by gustavohenke** [comment]
@getuliojr 

> Opa,
> Me pede via gitter/e-mail a senha da nossa conta do Medium pra postarmos lá.

**Comment by getuliojr** [comment]
@gustavohenke eu já pedi por la e passei meu email tambem. :)

**Comment by getuliojr** [comment]
Texto publicado.
