### ISSUE TITLE
Links para faq no index.md corrigidos

### ISSUE THREAD

**Issue by rogeriopvl** [nodejs/nodejs-pt#22]
https://github.com/iojs/website/pull/194

Fiz este pull request para corrigir os links no `index.md` que estavam a apontar para a raiz do site (e que acabavam por resolver para a versão em inglês).

Eles precisam de um +1 do nosso WG para aprovar o PR.

Alguém pode aprovar pff?

**Comment by gustavohenke** [comment]
Feito!

**Comment by rogeriopvl** [comment]
obrigado @gustavohenke . Vou dar o issue como fechado.
