### ISSUE TITLE
Traduzir artigo "How io.js built a 146 person, 27 language localization… in one day"

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#23]
É feito menção deste artigo na semana de 13 de Fevereiro, portanto o mesmo também deve ser traduzido. Abrindo uma tarefa aqui:

https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62

**Comment by Glauber** [comment]
Senhores segue o link da tradução https://medium.com/p/ee6aae2a90d4. Fiquei na dúvida se deveria traduzir o termo "issue" por ser uma coisa meio que própria do Github. O que vcs acham? Aguardo as observações sobre tudo.

**Comment by gustavohenke** [comment]
@Glauber, me pede via e-mail/Gitter a senha do nosso Twitter pra você postar na conta do Medium @iojs_pt, por favor.

**Comment by getuliojr** [comment]
Deixei os comentários sobre o texto na página traduzida, mas deixo o meu ok. :+1:

**Comment by Glauber** [comment]
@getuliojr fiz as correções mas confesso que a tradução de issue ainda me deixa desconfortável. E se formos mesmo traduzir, talvez fosse melhor escrever sempre o mesmo termo (foram sugeridos os termos "questão" e "item"), para manter uma coerência e pra ficar claro que faz menção a funcionalidade do github. Até que mais alguém dê sua opinião está feito como solicitado.

**Comment by JCMais** [comment]
@Glauber seria interessante criar um arquivo com termos comuns que devem, ou não, ser traduzidos.

**Comment by Glauber** [comment]
> @Glauber seria interessante criar um arquivo com termos comuns que devem, ou não, ser traduzidos.

estou de acordo @JCMais

**Comment by Glauber** [comment]
Pessoal a tradução já está pronta pra ir pro ar? Alguém tem mais algum comentário? Tá faltando um :+1:  pra marcar como translated.

**Comment by alexsantos** [comment]
:+1:

**Comment by cguedes** [comment]
Olá a todos. Este artigo não devia indicar que é uma tradução do artigo
original (e colocar link)?

As minhas desculpas se esta questão já foi debatida.

**Comment by Glauber** [comment]
Pessoal como não houve mais considerações estou dando por encerrado.
