### ISSUE TITLE
Traduzir texto: io.js Week of February 20th 2015

### ISSUE THREAD

**Issue by Glauber** [nodejs/nodejs-pt#24]
https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

**Comment by rogeriopvl** [comment]
Draft traduzido em https://medium.com/@iojs_pt/28fe6884685e

Confirmem por favor se existem alterações a fazer :)

**_Nota:**_ fiz a tradução de "user" como "usuário" dado que noutros posts encontrei essa palavra. Apesar de não ser português de portugal, na minha opinião é mais importante manter a coerência.

**Comment by rictorres** [comment]
Curiosidade: como seria em português de Portugal? :)

**Comment by ruiquelhas** [comment]
Utilizador.

**Comment by ruiquelhas** [comment]
Btw, fiz um pequeno comentário, mas não é nada que na minha óptica impeça a publicação, como tal, fica a minha aprovação.

:+1:

**Comment by getuliojr** [comment]
Fiz meus comentários sobre o item, mas deixo a aprovação: :+1:

**Comment by gustavohenke** [comment]
Fiz alguns comentários também, no mais, :+1:

**Comment by rictorres** [comment]
onde vcs estão fazendo os comentários? (devo ter perdido algo)

**Comment by getuliojr** [comment]
na própria página do Medium, não é o local correto ? Ao grifar o parágrafo ou item, faço o comentário para a melhoria. Normalmente ela entra como privada e apenas o criador da página pode ler e depois de confirmar ele pode alterar para público e todos tem acesso.

**Comment by gustavohenke** [comment]
> na própria página do Medium, não é o local correto?

Exato, @getuliojr. Inclusive vou adicionar isso na documentação do repositório, pra futura referência de novos colaboradores.

**Comment by rictorres** [comment]
boa, @getuliojr @gustavohenke 
também comentei lá no medium, mas :+1:

**Comment by rogeriopvl** [comment]
Fiz todas as alterações propostas excepto no último ponto das Reuniões.

Digam se concordam:
- @getuliojr eu acho que o nome dos Working Groups deve permanecer o original em inglês, isto porque se alguém quiser pesquisar mais sobre esse working group, não vai conseguir encontrar pelo nome traduzido.
- @gustavohenke As datas foram traduzidas apenas no nome do mês (ex. Feb -> Fev). De resto é apenas um formato diferente. Vale a pena por num formato diferente?

**Comment by gustavohenke** [comment]
Acho que um formato que seja comum aos colaboradores portugueses ou brasileiros seria interessante.
Aqui usamos DD/MM/YYYY.

**Comment by ruiquelhas** [comment]
Em Portugal o formato é o mesmo.

**Comment by rogeriopvl** [comment]
Alterei as datas para esse formato.

Artigo publicado.

**Comment by gustavohenke** [comment]
Valeu, @rogeriopvl!
