### ISSUE TITLE
Novo colaborador (@JCMais)

### ISSUE THREAD

**Issue by ruimarinho** [nodejs/nodejs-pt#25]
O @JCMais pediu para ser adicionado à org. `iojs-pt` na thread de i18n. Há algum processo definido para além de dar acesso como colaborador ao repo?

**Comment by gustavohenke** [comment]
Acho que adicionar o nome à lista de membros é o suficiente.

**Comment by ruimarinho** [comment]
Ok, fico a aguardar um PR do @JCMais :)

**Comment by JCMais** [comment]
@ruimarinho #26

**Comment by ruimarinho** [comment]
Done!
