### ISSUE TITLE
Perfis de redes sociais

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#3]
Quais perfis de redes sociais devemos utilizar?
Por exemplo, página no Facebook, Google+, alguma outra sugestão?
- Twitter: https://twitter.com/iojs_pt

**Comment by danilovaz** [comment]
Acredito que Twitter e Facebook sejam suficientes. São as que mais têm peso e poder de divulgação.

**Comment by ruimarinho** [comment]
Para já ficava pelo Twitter apenas. Até termos conteúdo e comunidade, não considero que seja necessária página do Facebook.

**Comment by gtramontina** [comment]
Concordo com @ruimarinho. Twitter para começar está de bom tamanho.

**Comment by ericdouglas** [comment]
@ruimarinho +1

Apenas Twitter de início!

**Comment by cguedes** [comment]
Olá a todos. Também concordo que se use apenas o Twitter.

**Comment by cguedes** [comment]
Já agora, podem-me adicionar como contributor? 

O mikael disse que [me adicionou](https://github.com/iojs/website/issues/125#issuecomment-73390998) mas não me parece.

**Comment by jpsc** [comment]
@ruimarinho +1

**Comment by gustavohenke** [comment]
Decidido então, alguma outra opinião?

**Comment by ruiquelhas** [comment]
:+1:
