### ISSUE TITLE
Proposta de Reconciliação com a Joyent / Node

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#30]
Seria importante todos acompanharem a discussão e lerem os textos propostos,afinal haverá uma votação para saber se devemos ou não unir as forças e as novas regras estabelecerão como essa comunidade seguirá.

Abaixo o link para a discussão da questão iojs/io.js#978

**Comment by gordalina** [comment]
Acho que seria interessante como iojs-pt apresentarmos o nosso voto na thread iojs/io.js#978
+1 para a reconciliação

**Comment by JCMais** [comment]
:+1: Ver o node.js se tornar um novo python 2.7 seria um pesadelo.

Mas eu sinceramente acho que, no momento, a Joyent não está disposta a aceitar o modelo de governança proposto, o que pode fazer com que essa reconciliação demoree[...]ee. :disappointed:

**Comment by gustavohenke** [comment]
Estou fechando esta issue.
Porque? Caso não tenham notado, nossa org agora é @nodejs :sunglasses:

A convergência está começando!

**Comment by JCMais** [comment]
Finalmente!

**Comment by rictorres** [comment]
:+1:

**Comment by Glauber** [comment]
:+1:
