### ISSUE TITLE
Traduzir comentário com informações de como contribuir

### ISSUE THREAD

**Issue by JCMais** [nodejs/nodejs-pt#32]
De https://github.com/iojs/website/pull/258#issuecomment-76962406

> Lets you localize the following however you like (a joke, url to your local group, both projects, etc.)
> `<!-- See something you like? Want to help? Visit https://github.com/iojs/website to contribute -->`

Precisamos discutir o que colocar aí. :smile:

**Comment by gordalina** [comment]
Só agora é que vi esta issue.
Enviei o seguinte PR https://github.com/iojs/website/pull/263
Já está merged, mas caso haja alguma alteração, [pode ser feita sem problemas](https://github.com/iojs/website/pull/263#issuecomment-77178952).

**Comment by gustavohenke** [comment]
Enviei PR para traduzir para pt-BR: iojs/website#290

**Comment by snostorm** [comment]
Can we get a +1 here or on https://github.com/iojs/website/pull/290 to merge? Minor enough I'll merge in 24 hours or so to give it time to be verified.
