### ISSUE TITLE
Traduzir: io.js Week of February 27th

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#33]
Link do original:
https://medium.com/node-js-javascript/io-js-week-of-february-17th-9422a589302a

**Comment by gustavohenke** [comment]
Este post está ultrapassado.
Alguém acha que vale a pena traduzir?

**Comment by getuliojr** [comment]
Sim acredito que todo o conteúdo deve ser traduzido. A proposta é que pelo menos o conteúdo semanais fossem traduzidos. Vejo sempre as mesmas pessoas participando, as mesmas traduzindo e contribuindo, apesar de ter uma lista grande de pessoas que se inscreveram para participar como colaboradores. Logo quem realmente entrou no oba oba, deve deixar a comunidade.

**Comment by Glauber** [comment]
Tb penso que deveria ser feito. E tb concordo com o @getuliojr de que está faltando rítimo. Tem tradução que não está publicada por falta de revisão.

**Comment by getuliojr** [comment]
Agora o artigo está com 1 mês de defasagem, foi colocado ha 20 dias e ninguem da comunidade pode traduzir. Eu não posso estar traduzindo todos e por isso temos uma comunidade. Se temos muitas pessoas que entraram por causa do 'momentum', então talvez o momento seja de tirar essas pessoas e procurar compromisso.

Este texto por exemplo, perdeu o sentido de ser traduzido depois de tanto tempo.

**Comment by rictorres** [comment]
Não acho que tenha perdido o sentido, esses posts ficarão acessíveis por pelo menos alguns anos.

**Sobre a participação da comunidade**
Muita gente realmente entrou por causa do _hype_ e nunca mais olhou o repo, mas até onde sei a proposta é "ajudar quando puder". Esse repo ainda é muito novo, pessoas que ainda não ajudaram podem muito bem contribuir no próximo mês. Só acho cedo pra definir quem tá participando ou não.

**Comment by getuliojr** [comment]
Muitas pessoas não tem tempo de ler o texto traduzido por alguém e dar um OK. Tem várias formas de ajudar e não apenas traduzindo, mas que tem gente que nunca tem postou um olá e está como administrador do grupo tem. E é esse ponto que acho complicado. O grupo está como semente e quem se candidatou para colaborar deve aparecer sim, dar um oi, postar um ou dois tópicos, comentar etc. Daqui 2 dias já teremos outro texto para traduzir e assumimos um compromisso semanal. Mas que tem atrasado e falhado. Uma pena, sei que há muita força aqui para virar a mesa, e as vezes o que precisa é de um puxão de orelha mesmo !

**Comment by Glauber** [comment]
Penso que todo mundo pode se organizar pra fazer duas ou três revisões por mês. Mesmo assim tem texto traduzido que demora para ser publicado por falta de review.  "Ajudar quando puder" quer dizer que você não pode estar fulltime envolvido porque tem outras atividades. Só que tem que fazer algo, por menor que seja. Passando dois meses e não deu pra pegar nenhuma tradução? O cara não pode ser admin de jeito nenhum. Do jeito que está daqui a pouco vai ter todo mundo deixando pra quem "puder". Hoje não dá pra saber com quem podemos contar e isso já está impactando no rendimento.

**Comment by luhad** [comment]
Olá pessoal, desculpe o "noobismo". Mas ainda não entendi como posso contribuir com as traduções ou como mando review etc.
Valeu !

**Comment by getuliojr** [comment]
Pode começar traduzindo a semana do dia 19 de junho @luhad está disponível para qualquer membro ajudar.
