### ISSUE TITLE
Traduzir texto: io.js Week of March 6th

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#34]
Outro artigo foi lançado na última sexta e necessita de tradução:
https://medium.com/node-js-javascript/io-js-week-of-march-6th-2f9344688277

**Comment by Glauber** [comment]
aguardando comentários em https://medium.com/@iojs_pt/193485df398b (alterei o link porque tinha gente que estava sendo direcionada à página errada)

**Comment by gustavohenke** [comment]
Oi @Glauber, por favor, posta na nossa conta do Medium @iojs_pt.

**Comment by Glauber** [comment]
> Oi @Glauber, por favor, posta na nossa conta do Medium @iojs_pt.

@gustavohenke estou só esperando o pessoal revisar pra colocar lá. Foi assim que definimos não foi?

**Comment by gustavohenke** [comment]
Pode deixar como rascunho, enquanto o pessoal revisa.
Depois de postado aparecerá no fim do post o seguinte:

![](http://i.imgur.com/5gSfM5m.png)

**Comment by Glauber** [comment]
> Pode deixar como rascunho, enquanto o pessoal revisa.
> Depois de postado aparecerá no fim do post o seguinte:

Pessoal o link no medium então https://medium.com/@iojs_pt/193485df398b, aguardo os comentários.

**Comment by Glauber** [comment]
Pessoal os textos estão ficando atrasados. Essa issue não fechou ainda por falta de revisão e o da semana do dia 27 ninguém nem pegou.

**Comment by gustavohenke** [comment]
Deixei algumas notas lá.

**Comment by Glauber** [comment]
> Deixei algumas notas lá.

feito

**Comment by getuliojr** [comment]
comentários finais adicionados, depois disso acho que pode ser publicado !

**Comment by Glauber** [comment]
:+1:

**Comment by Glauber** [comment]
> comentários finais adicionados, depois disso acho que pode ser publicado !

feito

**Comment by getuliojr** [comment]
:+1: tudo certo

**Comment by JCMais** [comment]
:+1: meu

**Comment by gustavohenke** [comment]
Publiquei!
