### ISSUE TITLE
Traduzir texto: 'io.js Week of March 13th'

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#35]
link:
https://medium.com/p/3b04b847cc7c

**Comment by getuliojr** [comment]
Já está traduzindo. Estou colocando para revisão:

https://medium.com/@iojs_pt/e3b5b4d3b2ff, 

Por favor olhem e dêem o feedback.

**Comment by Glauber** [comment]
:+1:

**Comment by gustavohenke** [comment]
:+1:

**Comment by gustavohenke** [comment]
Vamos só aguardar o post da issue #34 ser publicado antes de publicar este, beleza?

**Comment by getuliojr** [comment]
Correções sugeridas feitas e texto publicado.
