### ISSUE TITLE
Link to Semver

### ISSUE THREAD

**Issue by raphaelpor** [nodejs/nodejs-pt#36]
The Semver link on ["faq.html"](https://iojs.org/pt_BR/faq.html), have to be: http://semver.org/lang/pt-BR/.

**Comment by gustavohenke** [comment]
Oi Raphael. Você pode reportar as issues em português mesmo.
Em todos casos, obrigado por nos lembrar deste detalhe.

**Comment by raphaelpor** [comment]
Ok @gustavohenke!
Obrigado pelo retorno. :)

**Comment by JCMais** [comment]
Merged :+1:
