### ISSUE TITLE
Traduzir artigo: "io.js Week of March 20th"

### ISSUE THREAD

**Issue by getuliojr** [nodejs/nodejs-pt#37]
Pessoal, 

Tenho percebido que a comunidade não está ativa, quem se propôs a ajudar, poucos realmente estão. Toda semana os artigos tem sido traduzidos pelas mesmas pessoas e deveríamos ter 14 pessoas. Estou novamente colocando o artigo semanal para tradução e gostaria de ver novas pessoas que ainda não traduziram nada de se prontificar.

Abaixo texto para tradução:
https://medium.com/node-js-javascript/io-js-1-6-release-1df38cf64e6c

**Comment by gustavohenke** [comment]
Post para revisão:
https://medium.com/@iojs_pt/4e24c3e15508

**Comment by ruiquelhas** [comment]
Fiz alguns comentários ao draft.

**Comment by ruiquelhas** [comment]
Fiz alguns comentários ao draft.

**Comment by rictorres** [comment]
Adicionei minhas observações lá. Bom trabalho, @gustavohenke

**Comment by gustavohenke** [comment]
Alterações sugeridas realizadas!

**Comment by JCMais** [comment]
Nada a acrescentar da minha parte :+1:

**Comment by gustavohenke** [comment]
Para não ficar defasado como outros posts, já publiquei, mesmo sem os 2 OK que decidimos como necessário.

Link:
https://medium.com/@iojs_pt/io-js-semana-de-20-de-mar%C3%A7o-4e24c3e15508

**Comment by rictorres** [comment]
Ficou ótimo, @gustavohenke !
