### ISSUE TITLE
Traduzir artigo: "io.js Week of March 27th"

### ISSUE THREAD

**Issue by Glauber** [nodejs/nodejs-pt#38]
Link do original https://medium.com/node-js-javascript/io-js-week-of-march-27th-9555f36bbb9a

**Comment by ruimarinho** [comment]
Pronto para revisão.

**Comment by gustavohenke** [comment]
Posta aí o link pro pessoal, @ruimarinho ;)

**Comment by rictorres** [comment]
No aguardo do link :}

**Comment by ruimarinho** [comment]
Oops -- https://medium.com/@iojs_pt/38709b57bcea

**Comment by ruiquelhas** [comment]
:+1:

**Comment by gustavohenke** [comment]
Tirando as diferenças pt-PT e pt-BR, pra mim está ótimo.

**Comment by rictorres** [comment]
:+1:

**Comment by JCMais** [comment]
:+1:

**Comment by ruimarinho** [comment]
Publicado em https://medium.com/@iojs_pt/io-js-semana-de-27-de-mar%C3%A7o-38709b57bcea! Obrigado pelo feedback! :)

**Comment by gustavohenke** [comment]
Obrigado galera, essa foi rápida!
