### ISSUE TITLE
Plataforma de blog

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#4]
Qual plataforma de blog devemos utilizar?
Algumas sugestões:
- Ghost (deve ser hospedado)
- Wordpress.com
- GitHub pages
  - [Jekyll](http://jekyllrb.com)
  - [Hexo](http://hexo.io/)
- Medium

**Comment by ericdouglas** [comment]
- GitHub pages (usando Hexo)

**Comment by gustavohenke** [comment]
Eu pessoalmente prefiro algo que diminua a possibilidade de erro entre os diversos colaboradores do projeto. Para que todos sejam capazes de ajudar sem muitas dificuldades.

Isto significa usar ou Wordpress.com ou Medium.

**Comment by ericdouglas** [comment]
Ótimo @gustavohenke , assim podemos focar no conteúdo!

Voto no Medium!

**Comment by rogeriopvl** [comment]
+1 para o medium

**Comment by danilovaz** [comment]
+1 Medium

Além de ser fácil editar e ter uma interface muito usual; o Medium já se tornou uma big referência para desenvolvedores procurarem bons conteúdos.

**Comment by ruimarinho** [comment]
+1 para Medium.

**Comment by gtramontina** [comment]
Medium então?

**Comment by cguedes** [comment]
+1 medium

**Comment by jpsc** [comment]
Para mim também voto medium.
Fará sentido criar uma conta iojs_pt para as traducões dos blog posts ?

**Comment by erickpatrick** [comment]
+1 Medium

Além do mais, agora, ele conta com um botão próprio para tradução dos artigos presentes lá. Vejam o [os passos necessários e as dicas](https://medium.com/the-story/translate-medium-359ebb19d738) que o próprio pessal do Medium publicou sobre a possibilidade das traduções.

**Comment by jpsc** [comment]
@ericdouglas eu acho que isso não deve ser a solucao mais prática. cada vez que quiseremos traduzir um novo post temos de enviar um email para Medium ?

**Comment by gustavohenke** [comment]
+1 Medium.

Mas, tenho que concordar com o @jpcarmona, pode ficar um pouco chato este processo de esperar respostas da equipe do Medium.

**Comment by rogeriopvl** [comment]
Eu acho que é melhor criar uma conta própria para não ficarmos dependentes do Medium sempre que quisermos postar.

A não ser claro, que exista outra maneira em que não seja preciso enviar email e seja de forma automática.

**Comment by ruimarinho** [comment]
A ideia do @erickpatrick era gira se não fosse tão manual. Estou com o @rogeriopvl, mais vale criar uma conta à parte, até porque nem sei se é possível criar conteúdo exclusivamente num idioma (português) sem ter o artigo no idioma "original" (inglês).

**Comment by gustavohenke** [comment]
Criamos uma conta iojs_pt lá então? Pra ficar igual ao Twitter.

**Comment by gustavohenke** [comment]
Foi: https://medium.com/@iojs_pt

**Comment by erickpatrick** [comment]
Não, você só manda e-mail para eles habilitarem a funcionalidade de tradução no perfil de vocês. Foi um meio deles prevenirem que qualquer um saísse traduzindo as coisas, colocando algo nada a ver.

Após enviar o e-mail com seus nomes de usuários, eles responderão, confirmando a nova funcionalidade, ou não, para os usuários de vocês. Depois de confirmado, toda vez que acessar alguma publicação, você terá um novo botão na interface do Medium, onde você poderá trabalhar na versão traduzida da publicação.

**Comment by ruimarinho** [comment]
@erickpatrick e dá para criar conteúdo que não tenha o original em inglês?

Btw, este é bastante recente mas algo que também podemos considerar no futuro: http://hubpress.io/index.html

**Comment by erickpatrick** [comment]
Sim, dá. Aí, o ideal seria criar uma coleção dentro do próprio Medium, para agrupar todos essas publicações originais.
