### ISSUE TITLE
Traduzir: io.js Week of April 3rd

### ISSUE THREAD

**Issue by ruimarinho** [nodejs/nodejs-pt#40]
https://medium.com/node-js-javascript/io-js-week-of-april-3rd-a4e1fe0c38c1

**Comment by gustavohenke** [comment]
Ping @Glauber

**Comment by Glauber** [comment]
Aguardando coments senhores https://medium.com/p/71ac2a58f981/

**Comment by ruiquelhas** [comment]
Sugeri algumas fixes.

**Comment by ruimarinho** [comment]
@Glauber deixei as minhas sugestões!

**Comment by Glauber** [comment]
> Sugeri algumas fixes.

Acatadas.

> @Glauber deixei as minhas sugestões!

Dá uma olhada lá porque tem algumas que eu ainda quero a tua opinião (ou do pessoal claro).

**Comment by getuliojr** [comment]
+1 pode publicar

**Comment by JCMais** [comment]
:+1:

**Comment by ruimarinho** [comment]
:+1:

**Comment by Glauber** [comment]
publicado

**Comment by rictorres** [comment]
boa!
