### ISSUE TITLE
Traduzir: io.js Week of April 10th

### ISSUE THREAD

**Issue by Glauber** [nodejs/nodejs-pt#42]
https://medium.com/node-js-javascript/io-js-week-of-april-10th-cbf6cf32409

**Comment by getuliojr** [comment]
Texto traduzido. Aguardando revisão por parte da comunidade:

https://medium.com/@iojs_pt/210f06bdd723

**Comment by rictorres** [comment]
sugestões adicionadas.

**Comment by ruimarinho** [comment]
Feedback adicionado.

**Comment by getuliojr** [comment]
Sugetões alteradas e texto publicado.
