### ISSUE TITLE
Traduzir "io.js Week of April 24th"

### ISSUE THREAD

**Issue by JCMais** [nodejs/nodejs-pt#44]
Link do original: https://medium.com/node-js-javascript/io-js-week-of-april-24th-bd67dcbdfa65

**Comment by gustavohenke** [comment]
Resolvi traduzir isto, mesmo atrasado...: https://medium.com/@iojs_pt/c7f0cbf184a7
Feedbacks por favor!

**Comment by JCMais** [comment]
:+1: após as correções.

**Comment by gustavohenke** [comment]
Como estamos nos atrasando muito com as traduções, vou fazer as correções e depois liberar o post.

**Comment by gustavohenke** [comment]
Tá lá: https://medium.com/@iojs_pt/io-js-semana-de-24-de-abril-c7f0cbf184a7
