### ISSUE TITLE
Traduzir "io.js News" (Semana 15-05-2015)

### ISSUE THREAD

**Issue by ruimarinho** [nodejs/nodejs-pt#48]
https://github.com/nodejs/evangelism/blob/master/weekly-updates/weekly-update.2015-05-15.md

Tradução em https://medium.com/@iojs_pt/4bb8ddc2d398.

**Comment by gustavohenke** [comment]
Deixei com a label "reviewing" pra equipe ver que tem feedback pra dar.

**Comment by JCMais** [comment]
:+1:, e que ótima notícia!

**Comment by rictorres** [comment]
:+1:

**Comment by rands0n** [comment]
:+1:

**Comment by rictorres** [comment]
updates?

**Comment by ruimarinho** [comment]
Obrigado por me relembrares @rictorres :) publicado - https://medium.com/@iojs_pt/io-js-novidades-4bb8ddc2d398.

**Comment by rictorres** [comment]
boa, @ruimarinho :+1:
