### ISSUE TITLE
Traduzir "io.js Week of May 22nd"

### ISSUE THREAD

**Issue by rictorres** [nodejs/nodejs-pt#49]
https://medium.com/node-js-javascript/io-js-week-of-may-22nd-27905fd0cf8c

**Comment by tegon** [comment]
Traduzi esse, quando alguém puder dar uma olhada:

https://medium.com/@iojs_pt/b748f4cefc0

**Comment by gustavohenke** [comment]
Fiz algumas considerações lá @tegon

**Comment by JCMais** [comment]
Tudo ok da minha parte :+1:

**Comment by gustavohenke** [comment]
Tudo OK agora :+1: pode publicar!

**Comment by tegon** [comment]
Publicado! https://medium.com/@iojs_pt/io-js-semana-de-22-de-maio-b748f4cefc0
