### ISSUE TITLE
Tradução "io.js Week of February 6th 2015"

### ISSUE THREAD

**Issue by gustavohenke** [nodejs/nodejs-pt#5]
~~**Atenção:** é necessário pensar antes qual a plataforma de blog que será usada. Veja issue #4 para esta discussão.~~

Link para o post a ser traduzido:
https://medium.com/node-js-javascript/io-js-week-of-february-6th-2015-e185388549a4

**Comment by gustavohenke** [comment]
Se alguém quiser ir começando esta tarefa, me mande e-mail (gustavo@injoin.io) ou então fale comigo inbox no Gitter pra passar a senha do Twitter (usado pra fazer login na conta do Medium).
Isto até que tenhamos resolvido a issue #7.

**Comment by danilovaz** [comment]
inbox @gustavohenke  :+1: :smile:

**Comment by danilovaz** [comment]
traduzi o post, peço a ajuda de quem puder revisar o texto caso encontre algum erro ou typo: https://medium.com/@iojs_pt/a09a125faeb4

Lembrando que para ver o post, precisa ter uma conta no Medium. Está como rascunho, após a revisão de vocês e o OK, podemos postar.

Valeu :smiley: :+1:  :book: 

cc @iojs/iojs-pt

**Comment by gustavohenke** [comment]
Fiz apenas um comentário lá, de resto acho que pode ser publicado!

**Comment by danilovaz** [comment]
Não estou conseguindo ver o seu comentário no artigo. Acredito ser um bug porque ontem eu respondi alguns notes lá normalmente. Se puder, me mande a consideração no Gitter. Valeu @gustavohenke !

**Comment by danilovaz** [comment]
Fiz as alterações no texto conforme indicaram nos notes do Medium. Com base nisso, publiquei nosso primeiro post no Medium: https://medium.com/@iojs_pt/io-js-semana-de-06-de-fevereiro-de-2015-a09a125faeb4 e estou fechando essa issue.

Vamos para mais uma :smile: :+1:
