### ISSUE TITLE
Traduzir "io.js Week of May 29th"

### ISSUE THREAD

**Issue by rictorres** [nodejs/nodejs-pt#50]
https://medium.com/node-js-javascript/io-js-week-of-may-29th-89bdeace6056

**Comment by ruiquelhas** [comment]
Draft: https://medium.com/@iojs_pt/6948b99a9c6

**Comment by rictorres** [comment]
:+1:

**Comment by JCMais** [comment]
:+1:

**Comment by ruiquelhas** [comment]
Publicado.
