### ISSUE TITLE
Divisão pt-br / pt-pt

### ISSUE THREAD

**Issue by ericdouglas** [nodejs/nodejs-pt#6]
Devemos definir como será feita essa divisão.

Sugestões?

**Comment by danilovaz** [comment]
Acho importante essa divisão. O padrão mais utilizado tanto em docs traduzidas quanto em qualquer coisa que se refira a idioma na web é pt-pt e pt-br

**Comment by ruimarinho** [comment]
Em termos de documentação, no repositório do website já existe uma separação entre pt-pt e pt-br. Em termos de organização de issues, penso que temos de discutir em comunidade porque o mesmo contexto se aplica a `iojs-es`(es-ES, es-MX, etc). O ideal, na minha opinião, era conseguirmos uniformizar este aspecto.

Particularmente no caso da comunidade (conferências, palestras, etc) essa distinção se calhar ganha mais relevo, embora seja interessante haver troca de ideias entre PT e BR :)

**Comment by danilovaz** [comment]
@ruimarinho a troca dei ideias é realmente importante, o "problema" é que as duas linguas por mais que a base seja a mesma, existem pequenas diferenças e isso no âmbito mais técnico deve ser levado em consideração. Mas nada impede de ter essa troca de ideias, claro.

**Comment by ruimarinho** [comment]
De acordo. Podíamos começar por ter, p.e., um README na root a apontar para `pt-BR/README.md` e `pt-PT/README.md`.

**Comment by gtramontina** [comment]
Eu, particularmente, não me importo com a "mistura" das línguas. Acredito que se houver alguma divisão, que seja no que diz respeito a eventos locais.

**Comment by ericdouglas** [comment]
Vejam uma [nota](https://github.com/iojs/website/issues/125#issuecomment-73392158) do @mikeal sobre "Localização X Língua".

Essa sugestão do @ruimarinho é interessante, e assim podemos listar nos respectivos READMEs, os materiais criados em cada localização.

Sobre contas diferentes nas redes sociais, creio que não seja necessário, pois podemos divulgar os materiais e fazer uma sinalização `[pt-br]` ou `[pt-pt]` para notificar de onde veio o material.

**Comment by jpsc** [comment]
@danilovaz concordo contigo, embora seja identica existem termos que diferem. 

@ericdouglas será que e assim tão importante saber de que parte vem o material? Acho que quem percebe a língua percebe a outra.

**Comment by ruiquelhas** [comment]
> The expectation is that the team around each language can work together to produce several localizations.

Existindo a possiblidade e a disponibilidade para produzir a documentação de ambas as localizações, creio que será esse o caminho ideal.

**Comment by danilovaz** [comment]
@ruimarinho Concordo, muito bom.

**Comment by gustavohenke** [comment]
Como um exemplo de divisão de conteúdo, acho que a Wikipedia funciona muito bem.
Em um artigo comum para as duas culturas, geralmente a palavra na outra cultura está lá, como:

> [...] xyz (também conhecido como abc em português brasileiro)

**Comment by jpsc** [comment]
Eu acho que é mais do que palavras singulares. Mas podemos fazer teste nos primeiros artigos que traduzirmos.

**Comment by danilovaz** [comment]
@gustavohenke podemos testar assim. Como o @jpcarmona disse, fazemos um teste nos primeiros artigos fazendo referência às diferenças dos dois idiomas quando surgir. A pergunta que fica é, qual das duas será a "principal"? Por exemplo, um artigo será inteiro em pt-br com referências ao pt-pt quando surgir palavras diferentes ou o inverso?

**Comment by fixe** [comment]
Uma pergunta: os commits/PRs deste repositório não deviam ser na mesma em Inglês?

**Comment by jpsc** [comment]
Eu pensei exactamente nisso quando fiz o meu. Para mim torna-se mais fácil ser em Inglês.

**Comment by danilovaz** [comment]
@jpcarmona @fixe não sei se seria o melhor ser em inglês, afinal no repo é unânime o português, não?

**Comment by gustavohenke** [comment]
@danilovaz +1 para tudo em português!

**Comment by fixe** [comment]
Acho estranho ver mensagens de commit em PT. Na minha opinião apenas os conteúdos deviam ser traduzidos.

**Comment by danilovaz** [comment]
Na minha opinião que as mensagens de commit, PRs, labels etc são para controle da própria comunidade e as pessoas que mantém o projeto. Se a maioria que contribui, tem como idioma principal o português, não vejo razão de usar o inglês. A não ser que outra pessoa que não fale português ajude nas traduções ou discussões, mas acho isso difícil.

Voto por ser tudo em português. Mas não teria problemas se os commits, PRs e labels fossem em inglês, só acho desnecessário.

**Comment by ruimarinho** [comment]
Confesso que acho um pouco estranho ver commits como  "Merge pull request X" misturados com commits em português. É uma preferência pessoal, claro, pela mesma razão que não escrevo código em português também. A minha sugestão é:
1. Processos em inglês (commit messages, labels, etc).
2. Conteúdo em português (descrições de PRs, documentação, etc).

Todos os colaboradores deste repo com certeza dominam o inglês e também não se coloca nenhum entrave a qualquer novo membro da comunidade pois usufruem na mesma do conteúdo em português.

**Comment by gustavohenke** [comment]
Vamos fazer uma votação?

1 - Mensagens de commits e PRs em português
2 - Mensagens de commits e PRs em inglês

**Comment by ruiquelhas** [comment]
Na minha modesta opinião, acho que só os "deliverables" é que devem ser em Português. Tudo o que seja discussão, issues e pull requests, devem ser em Inglês. Do ponto de vista de partilha de conhecimento inter-grupo, particularmente ao nível de processo, deixa de existir a barreira linguistica, sendo que estou certo que existe muito a aprender com outros grupos e vice-versa.

**Comment by jpsc** [comment]
@ruimarinho exactamente.

Voto na segunda opção.

**Comment by danilovaz** [comment]
voto na opção 1

**Comment by ruimarinho** [comment]
Estou com o @ruiquelhas - maior intercomunicação entre diferentes comunidades (p.e. alguém que vem do estrangeiro para o nosso país pode acompanhar a comunidade io.js-pt) e assim até podemos mencionar alguém do TC para dar input sobre determinados temas.

**Comment by danilovaz** [comment]
então acho que fechou? a maioria pelo visto vota em -> labels, commits e demais em inglês e somente conteúdo e nossas conversas aqui, em português, correto?

**Comment by gustavohenke** [comment]
Por mim é isso.
Discussão nas issues fica melhor se for em português, a não ser que envolva algum não falante do idioma.

**Comment by danilovaz** [comment]
Então ok, mudei as labels para inglês. Commits, PRs e demais a partir de agora em inglês e somente conteúdo e assuntos que dizem respeito aos mantenedores ficam em português. Todos ficaram de acordo dessa forma, correto?

**Comment by ericdouglas** [comment]
@danilovaz correto!

**Comment by danilovaz** [comment]
issue fechada então =) vamos ao trabalho agora rs :smile:
