### ISSUE TITLE
Traduzir "io.js and Node.js Week of July 24th"

### ISSUE THREAD

**Issue by rictorres** [nodejs/nodejs-pt#63]
https://medium.com/node-js-javascript/io-js-week-of-july-24th-93238b278a8d

**Comment by rictorres** [comment]
https://medium.com/@iojs_pt/3a3d1e67b84d

**Comment by ruiquelhas** [comment]
Deixei um comentário.

**Comment by gustavohenke** [comment]
por mim, :+1:

**Comment by JCMais** [comment]
:+1:, btw, io.js v3 será o último io.js? O próximo já será a próxima versão do Node, correto?

**Comment by rictorres** [comment]
https://medium.com/@iojs_pt/not%C3%ADcias-sobre-io-js-e-node-js-24-de-julho-3a3d1e67b84d

**Comment by rictorres** [comment]
@JCMais tudo indica que o próximo _major_ release (v4) será do Node.js.
esse artigo explica mais a fundo: https://medium.com/@nodesource/essential-steps-long-term-support-for-node-js-8ecf7514dbd
