### ISSUE TITLE
Traduzir "io.js and Node.js News — August 7th"

### ISSUE THREAD

**Issue by rictorres** [nodejs/nodejs-pt#65]
https://medium.com/node-js-javascript/io-js-and-node-js-news-august-7th-49d7c3f09810

**Comment by osvaldoabel** [comment]
@rictorres quero ajudar/contribuir. Tenho que publicar esse artigo traduzido no [medium](www.medium.com) ?

**Comment by gustavohenke** [comment]
Olá @Kanguanda, tudo bem se você criar o rascunho na sua conta do Medium primeiro?

Assim que estiver quase aprovado o post, te envio o acesso para a conta da equipe.
