### ISSUE TITLE
Inclusão de Novos Membros para Realização de Traduções

### ISSUE THREAD

**Issue by glaucia86** [nodejs/nodejs-pt#69]
@gustavohenke @cguedes @danilovaz @ericdouglas @erickpatrick @getuliojr @Glauber @gtramontina @jpsc @JCMais @rictorres @rogeriopvl @ruimarinho @ruiquelhas @gordalina @fixe 

Abri uma PR aqui https://github.com/nodejs/nodejs.org/pull/1947 e já foi feito o merge para a master.
No **README.md** comenta que se faça alguma contribuição para o projeto, para que vocês possam saber se o português está correto e em seguida falar com algum membro daqui para que possam adicionar.
Estou enviando essa mensagem aqui para saber se haveria a possibilidade em incluir eu @glaucia86 e @Drieger como membros para que possamos dar continuidade nas traduções. Quero aproveitar os feriados a frente para fazer as traduções.

Desde já agradeço a todos! :D

**Comment by gustavohenke** [comment]
Olá 🙂,
Infelizmente cheguei tarde pra revisar o PR. Mas parece estar tudo OK.

Sobre adicionar pessoas novas: acredito que tenha que ser solicitado à administração Node.js Foundation. Tenho estado um tanto inativo por aqui ultimamente, então é só um palpite...
O que posso fazer, no entanto, é adicionar vocês a este repositório. O que não dá oportunidade de fazer muito.

**Comment by glaucia86** [comment]
Sem problemas @gustavohenke. Alguma indicação de quem eu possa estar procurando do Node.js Foundation e poder pingar aqui?

**Comment by gustavohenke** [comment]
Não que eu lembre. Talvez valha a pena criar um post na equipe [Localization](https://github.com/orgs/nodejs/teams/localization)?
Mas recomendo pesquisar antes. Infelizmente não tenho muita noção de como anda isso.

**Comment by glaucia86** [comment]
Blz. Vou postar lá. Muito obrigada @gustavohenke. Só me passe o link do pessoal da Localization. Pois o que está acima dá 404. Fechando a issue aqui

**Comment by gustavohenke** [comment]
Ah, provavelmente dá 404 pois não és membro da fundação ainda 😅 

Vou reabrir pra caso alguém saiba com quem falar sobre...

**Comment by glaucia86** [comment]
Valeu @gustavohenke <3

**Comment by cezaraugusto** [comment]
@glaucia86 @Drieger parabéns pela iniciativa! criei o https://github.com/nodejs/nodejs.org/pull/1953 e o https://github.com/nodejs/nodejs.org/pull/1954.

**Comment by gustavohenke** [comment]
@cezaraugusto vou ir revisando quando der tempo 😃

**Comment by JCMais** [comment]
@Drieger @glaucia86 @cezaraugusto eu consigo adicionar vocês neste repo, mas não tenho como fazer o mesmo para o time. Eu estou um pouco por fora de como está o processo para adicionar novos membros nos times, porém mandei uma msg no slack que geralmente tem uma galera da org ativa, e também abri essa issue no repo do i18n: https://github.com/nodejs/i18n/issues/189

**Comment by glaucia86** [comment]
> @glaucia86 @Drieger parabéns pela iniciativa! criei o [nodejs/nodejs.org#1953](https://github.com/nodejs/nodejs.org/pull/1953) e o [nodejs/nodejs.org#1954](https://github.com/nodejs/nodejs.org/pull/1954).



> @glaucia86 @Drieger parabéns pela iniciativa! criei o [nodejs/nodejs.org#1953](https://github.com/nodejs/nodejs.org/pull/1953) e o [nodejs/nodejs.org#1954](https://github.com/nodejs/nodejs.org/pull/1954).

Coisa Linda! Bora nos movimentar! :D

**Comment by glaucia86** [comment]
> @Drieger @glaucia86 @cezaraugusto eu consigo adicionar vocês neste repo, mas não tenho como fazer o mesmo para o time. Eu estou um pouco por fora de como está o processo para adicionar novos membros nos times, porém mandei uma msg no slack que geralmente tem uma galera da org ativa, e também abri essa issue no repo do i18n: [nodejs/i18n#189](https://github.com/nodejs/i18n/issues/189)

Sem problemas @JCMais. Enquanto isso, vamos adiantando nas traduções aqui. Valeu mesmo! :)

**Comment by glaucia86** [comment]
O @fhemberger fez uma solicitação por aqui: https://github.com/nodejs/nodejs.org/pull/1953.
Com base nisso, estarei fechando esse Issue.
