### ISSUE TITLE
Compartilhamento de senhas

### ISSUE THREAD

**Issue by gtramontina** [nodejs/nodejs-pt#7]
Que tal manter senhas e outros segredos nesse mesmo repositório usando https://github.com/StackExchange/blackbox?

**Comment by ruimarinho** [comment]
Por mim é excelente :) https://keybase.io/ruimarinho

**Comment by gustavohenke** [comment]
Quando definirmos isso eu compartilho e-mail e Twitter que criei.
Por enquanto, ainda não entendi como funciona o Keybase e o Blackbox achei MUITA coisa pra ler :cry:

**Comment by gustavohenke** [comment]
@ruimarinho Acredito ter entendido o keybase! :)
Eu encripto algo com o seu usuário, e apenas você vai conseguir desencriptar. É isto?

**Comment by ruimarinho** [comment]
Sim. O keybase funciona através de gpg e nada mais. A única vantagem é que podes ter mais confiança que a chave pública de gpg que lá está é realmente minha :) "web of trust". Na realidade, isto apenas implica que encriptes a password com a minha chave pública e de seguida podes enviá-la através de um canal não seguro, como email ou irc.

O blackbox apenas tem a vantagem de automatizar este processo para que o repositório contenha todas as passwords que dispomos encriptadas com as chaves públicas de todos os colaboradores.

**Comment by gustavohenke** [comment]
Certo.
Gosto da possibilidade de usar o keybase, mas como ele está com inscrições fechadas, por enquanto, quem quiser senha do Twitter @Iojs_pt, pode me pedir via e-mail ou inbox no gitter.

**Comment by ruimarinho** [comment]
@gustavohenke acabei de receber 4 convites, por isso posso partilhá-los :) se cada um receber mais alguns conseguimos cobrir a org toda. Enviei-te um convite (estou pelo Gitter também).

**Comment by JCMais** [comment]
@ruimarinho poderias me enviar um convite?

**Comment by ruimarinho** [comment]
Done @JCMais.

**Comment by gordalina** [comment]
tenho 8 convites keybase para quem quiser.

**Comment by getuliojr** [comment]
Poderia me enviar uma Samuel ?

2015-02-27 14:23 GMT-03:00 Samuel Gordalina notifications@github.com:

**Comment by gordalina** [comment]
@getuliojr qual o email?

**Comment by getuliojr** [comment]
Poderia ver no meu perfil ? Prefiro do que deixar registrado por comentário.

**Comment by gordalina** [comment]
@getuliojr enviado

**Comment by Glauber** [comment]
Pode me enviar uma @gordalina ?

**Comment by gordalina** [comment]
@Glauber enviado

**Comment by rictorres** [comment]
@gordalina @ruimarinho ainda possuem convites para o keybase? :)

**Comment by ruimarinho** [comment]
Sim, enviado!

**Comment by rictorres** [comment]
muito obrigado!!

**Comment by G1lmar** [comment]
Alguém pode me enviar um convite keybase?
