### ISSUE TITLE
[pt-BR] Website: Translate "about" session

### ISSUE THREAD

**Issue by Drieger** [nodejs/nodejs-pt#71]
Algumas iniciativas para traduzir o site para pt-BR vem acontecendo nos últimos dias. Acredito que possamos organizar melhor o que falta abrindo issues relacionadas. Este primeiro tópico é dedicado a  seção "[Sobre](https://nodejs.org/pt-br/about/)" do website.

**Arquivos para tradução:**
- [ ] community.md
- [x] governance.md (https://github.com/nodejs/nodejs.org/pull/1981)
- [x] index.md (https://github.com/nodejs/nodejs.org/pull/1974)
- [ ] privacy.md
- [ ] releases.md
- [ ] resources.md
- [ ] trademark.md
- [ ] working-groups.md

**Obs:**
Os arquivos originais encontram-se em https://github.com/nodejs/nodejs.org/tree/master/locale/en/about

**Comment by glaucia86** [comment]
@Drieger amei a criação da Issue. Assim que voltar de viagem... já vou começar a pegar alguns para traduzir!

**Comment by Drieger** [comment]
Fiz a tradução do `index.md`.
Quem quiser revisar e dar sugestões: https://github.com/nodejs/nodejs.org/pull/1974

**Comment by glaucia86** [comment]
> Fiz a tradução do `index.md`.
> Quem quiser revisar e dar sugestões: [nodejs/nodejs.org#1974](https://github.com/nodejs/nodejs.org/pull/1974)

Vou dar uma olhada agora @Drieger

**Comment by Drieger** [comment]
Vou iniciar a tradução da seção de governança (`governance.md`)

**Comment by glaucia86** [comment]
@Drieger voltei de viagem essa semana. Devo dar prosseguimento nas traduções esse final de semana para ajudar! :)

**Comment by Drieger** [comment]
Tradução do `governance.md` para revisão e sugestões: https://github.com/nodejs/nodejs.org/pull/1981

**Comment by nelsonmfinda** [comment]
@Drieger Como vai?
Gostaria de contribuir na tradução, pelo que vi, as secções marcadas nesta issue já foram traduzidas certo?

**Comment by vanribeiro** [comment]
Gostaria de colaborar com a tradução do tópicos:
**privacy.md
releases.md**
É possível?

**Comment by LeuAlmeida** [comment]
@Drieger posso colaborar com o arquivo **working-groups.md**?

**Comment by Drieger** [comment]
Oi @LeuAlmeida, pode colaborar sim sugiro dar uma olhada no https://github.com/nodejs/nodejs-pt/issues/80#issuecomment-616627117 pois as traduções estão sendo movidas para o crowdin

**Comment by Drieger** [comment]
estou fechando a issue, para manter todas as traduções centralizadas no crowding, conforme https://github.com/nodejs/nodejs-pt/issues/80#issuecomment-616627117
