### ISSUE TITLE
[pt-BR] Website: Translate "download" session

### ISSUE THREAD

**Issue by Drieger** [nodejs/nodejs-pt#72]
Algumas iniciativas para traduzir o site para pt-BR vem acontecendo. Este tópico foi criado para organizar a tradução da seção "[Download](https://nodejs.org/pt-br/download/)" do website.

**Arquivos para tradução:**

- [x] current.md (nodejs/nodejs.org/pull/2234)
- [x] index.md (nodejs/nodejs.org#2208)
- [x] package-manager.md (nodejs/nodejs.org#2190)
- [x] releases.md (nodejs/nodejs.org/pull/2235)

**Obs:**
Os arquivos originais encontram-se em https://github.com/nodejs/nodejs.org/tree/master/locale/en/download

**Comment by glaucia86** [comment]
@Drieger abrirei uma PR amanhã e farei o **package-manager.md**

https://github.com/nodejs/nodejs.org/blob/master/locale/en/download/package-manager.md

**Comment by maugravena** [comment]
Boa tarde,

Como está o andamento da tradução?
Como faço para ajudar?

**Comment by Drieger** [comment]
@maugravena, os passos são os seguintes

1. Clonar o repositório do https://github.com/nodejs/nodejs.org 
2. Copiar o conteúdo que deseja traduzir da pasta `locale/en` para a pasta `locale/pt-br`
3. Realizar as traduções e abrir um PR no repositório do nodejs/nodejs.org
4. Marcar @nodejs/nodejs-pt  para realizar a revisão do PR

Depois de feitas eventuais correções e aprovado o PR é incorporado ao código do site. Qualquer dúvida que tiver pode abrir abrir uma nova "Issue" aqui mesmo.

**Comment by maugravena** [comment]
Muito obrigado @Drieger

Ficou bem clara sua explicação!

**Comment by maugravena** [comment]
Olá pessoal,

Fiz a tradução da página package-manager.md.
revisão e sugestões em: [nodejs/nodejs.org#2190](https://github.com/nodejs/nodejs.org/pull/2190)

Abraços

**Comment by Drieger** [comment]
@maugravena muito obrigado pela contribuição. Acho que logo mais o pessoal já realiza a revisão. Já marquei o documento como traduzido e linkei o PR

**Comment by maugravena** [comment]
Olá,

Mais uma tradução, agora da página index.md
revisão e sugestões: [nodejs/nodejs.org#2208](https://github.com/nodejs/nodejs.org/pull/2208)

**Comment by maugravena** [comment]
Fala pessoal, 

Agora para finalizar essa sessão
Revisões para: [nodejs/nodejs.org#2234](https://github.com/nodejs/nodejs.org/pull/2234) / [nodejs/nodejs.org#2235](https://github.com/nodejs/nodejs.org/pull/2235)

Abraços

**Comment by Drieger** [comment]
Ótimo trabalho @maugravena. Assim que os dois PR forem aprovados e colocados em produção podemos finalizar este tópico :+1:

**Comment by Drieger** [comment]
Atualizei as labels da issue, uma vez que todas as páginas foram colocadas em produção. Agradecemos a todos pelo esforço nessa tarefa.

**Comment by Drieger** [comment]
estou fechando a issue, para manter todas as traduções centralizadas no crowding, conforme #80 (comment)
