### ISSUE TITLE
Including on README.md new Members

### ISSUE THREAD

**Issue by glaucia86** [nodejs/nodejs-pt#73]
Oi @gustavohenke 
Posso estar abrindo uma PR para incluir o nome de novos membros que estão realizando as traduções e ajudando na internacionalização para o português (incluso o meu nome)?

[https://github.com/nodejs/nodejs-pt](https://github.com/nodejs/nodejs-pt)

**Comment by JCMais** [comment]
@glaucia86 você deve 😄 

Se for possível, também mude de io.js para Node.js, o Readme está um "tantinho" desatualizado.

**Comment by glaucia86** [comment]
> @glaucia86 você deve 😄
> 
> Se for possível, também mude de io.js para Node.js, o Readme está um "tantinho" desatualizado.

Farei agora.

**Comment by glaucia86** [comment]
@JCMais feito. #74

**Comment by glaucia86** [comment]
Issue resolvida no PR #76
