### ISSUE TITLE
Habilitar C.I Travis no repositório - Nodejs-pt

### ISSUE THREAD

**Issue by glaucia86** [nodejs/nodejs-pt#78]
@gustavohenke @JCMais e @Drieger 

Estou abrindo essa issue aqui com a intenção de poder habilitar o C.I no Travis e poder criar alguns requisitos de commits, criações de branchs e aprovações de PR's.
Gostaria de saber com vocês, se me autorizam a realizar essas mudanças no **Settings** desse repositório e colocar C.I no repo.
Assim que eu tiver a aprovação de vocês, criarei uma nova PR para poder incluir essas regras no arquivo .travis.yml que criarei.

Fico no aguardo da aprovação de vocês aqui - se desejam criar essas regras ou não. Comentem a aprovação de vcs aqui nessa issue.

Abraço a todos.

**Comment by Drieger** [comment]
Acho a ideia bem legal, seria pra validar que tipo de situação. Os PRs de tradução, propriamente ditos, são feitos no nodejs.org :+1:

**Comment by glaucia86** [comment]
> Acho a ideia bem legal, seria pra validar que tipo de situação. Os PRs de tradução, propriamente ditos, são feitos no nodejs.org 👍

bem lembrado..... então não tem necessidade de colocar no travis. Mas, habilitei aqui q só podemos aprovar um determinado PR se tiver pelo menos a aprovação de 2 pessoas do time nodejs-pt.

**Comment by glaucia86** [comment]
Vou fechar a issue. Pois notei aqui q como nao se trata de um código em alguma linguagem. Nao tem como habilitar o travis com algumas regras de execução aqui.
E uma vez que já passa pelo pente fino do team core do node, como bem lembrado pelo @Drieger, realmente nao há necessidade de criar um arquivo .travis.yml nessa repo.
Porém, habilitei na parte de **Settings** desse repositório, algumas regras antes do nosso time aprovar um determinado PR. (configurei a branch: master e * significa qualquer branch criada por alguém aqui)

![image](https://user-images.githubusercontent.com/1631477/51471867-06852b00-1d5f-11e9-8ec7-4138a7ce283c.png)
